version: "2"
services:
  dl_nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - fpm
    depends_on:
      - fpm
      - db
    links:
      - db
  dl_fpm:
    build: ./fpm
    restart: always
    volumes:
      - ./app/public:/var/app/public
      - ./app/storage:/var/app/storage
    links:
      - db
  dl_db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oemjih
    restart: always
